# Generated by Django 4.0 on 2022-07-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_max', models.BooleanField(default=True)),
                ('storage_used_kB', models.PositiveBigIntegerField(default=0)),
                ('storage_max_kB', models.PositiveBigIntegerField(default=0)),
                ('bandwidth_upload_used_kB', models.PositiveIntegerField(default=0)),
                ('bandwidth_upload_max_kB', models.PositiveIntegerField(default=0)),
                ('bandwidth_download_used_kB', models.PositiveIntegerField(default=0)),
                ('bandwidth_download_max_kB', models.PositiveIntegerField(default=0)),
                ('files', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
