# Generated by Django 4.0 on 2022-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstoragedata',
            old_name='storage_max_kB',
            new_name='storage_max_B',
        ),
        migrations.RenameField(
            model_name='userstoragedata',
            old_name='storage_used_kB',
            new_name='storage_used_B',
        ),
        migrations.AlterField(
            model_name='userstoragedata',
            name='bandwidth_download_max_kB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstoragedata',
            name='bandwidth_download_used_kB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstoragedata',
            name='bandwidth_upload_max_kB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstoragedata',
            name='bandwidth_upload_used_kB',
            field=models.FloatField(default=0),
        ),
    ]
