# Generated by Django 4.0 on 2022-07-29 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0003_party_userpartylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoragedata',
            name='notifTypes',
            field=models.JSONField(default=['NULL']),
        ),
        migrations.AddField(
            model_name='userstoragedata',
            name='notificationsOn',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
