# Generated by Django 4.0 on 2022-07-31 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0005_alter_userstoragedata_notiftypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.party')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('do_sort', models.BooleanField(default=False)),
                ('do_auto_archive', models.BooleanField(default=False)),
                ('archive_by', models.CharField(max_length=256)),
                ('task_count', models.PositiveBigIntegerField(default=0)),
                ('archived_date', models.DurationField()),
                ('trash_date', models.DateTimeField()),
                ('kanban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.kanban')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstoragedata',
            name='task_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=256)),
                ('do_auto_archive', models.BooleanField(default=False)),
                ('archive_by', models.CharField(max_length=256)),
                ('timeToArchive', models.DurationField()),
                ('countToArchive', models.PositiveIntegerField(default=-1)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField()),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.taskcolumns')),
                ('kanban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.kanban')),
            ],
        ),
    ]
