# Generated by Django 4.0 on 2022-07-31 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_kanban_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('state', models.CharField(default='active', max_length=256)),
                ('do_auto_archive', models.BooleanField(default=False)),
                ('archive_by', models.CharField(blank=True, max_length=256)),
                ('timeToArchive', models.DateTimeField(blank=True)),
                ('countToArchive', models.PositiveIntegerField(default=-1)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('do_sort', models.BooleanField(default=False)),
                ('sort_by', models.CharField(default='M', max_length=16)),
                ('do_auto_archive', models.BooleanField(default=False)),
                ('archive_by', models.CharField(blank=True, max_length=256)),
                ('task_count', models.PositiveBigIntegerField(default=0)),
                ('archived_date', models.DateTimeField(blank=True)),
                ('trash_date', models.DateTimeField(blank=True)),
                ('kanban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.kanban')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='column',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='kanban',
        ),
        migrations.DeleteModel(
            name='TaskColumns',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.taskcolumn'),
        ),
        migrations.AddField(
            model_name='task',
            name='kanban',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.kanban'),
        ),
    ]
