# Generated by Django 4.0 on 2022-07-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0010_alter_task_column_alter_task_kanban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.party'),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
